
-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  coin_balance integer default 100,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for history
create table history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  captions jsonb,
  hashtags jsonb,
  best_time text,
  viral_potential integer,
  platform text,
  mood text,
  music_recommendations jsonb,
  roast text,
  scores jsonb,
  improvements jsonb
);

alter table history enable row level security;

create policy "Users can view their own history."
  on history for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own history."
  on history for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own history."
  on history for delete
  using ( auth.uid() = user_id );

-- Create a table for transactions (optional but good for audit)
create table transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  amount integer not null, -- positive for purchase, negative for spend
  description text,
  payment_id text -- from Razorpay or similar
);

alter table transactions enable row level security;

create policy "Users can view their own transactions."
  on transactions for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own transactions."
  on transactions for insert
  with check ( auth.uid() = user_id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, coin_balance)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 100);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- BACKFILL: Create profiles for users who signed up before this script was run
insert into public.profiles (id, full_name, avatar_url, coin_balance)
select 
  id, 
  raw_user_meta_data->>'full_name', 
  raw_user_meta_data->>'avatar_url', 
  100
from auth.users
on conflict (id) do nothing;

-- ENGAGEMENT FEATURES SCHEMA

-- 1. Daily Login Streak (Add columns to profiles)
alter table profiles 
add column if not exists last_login_date date,
add column if not exists streak_count integer default 0,
add column if not exists subscription_tier text default 'free';

-- 2. PvP Photo Challenge
create table challenges (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  theme text not null,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  status text default 'active' -- active, completed
);

create table challenge_entries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  challenge_id bigint references challenges(id) not null,
  user_id uuid references auth.users not null,
  image_url text not null,
  votes integer default 0,
  
  unique(challenge_id, user_id) -- One entry per user per challenge
);

-- RLS for Challenges
alter table challenges enable row level security;
create policy "Challenges are viewable by everyone." on challenges for select using (true);

-- RLS for Entries
alter table challenge_entries enable row level security;
create policy "Entries are viewable by everyone." on challenge_entries for select using (true);
create policy "Users can insert their own entries." on challenge_entries for insert with check (auth.uid() = user_id);
create policy "Users can update their own entries." on challenge_entries for update using (auth.uid() = user_id);

-- 3. Collab Finder (Add columns to profiles)
alter table profiles
add column if not exists niche text, -- e.g., 'Fashion', 'Tech', 'Fitness'
add column if not exists bio text,
add column if not exists looking_for_collab boolean default false,
add column if not exists contact_email text; -- For the "Connect" button

-- Create an index for faster collab searching
create index if not exists profiles_niche_idx on profiles(niche);


-- 4. Guest Usage Tracking
create table if not exists guest_usage (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ip_address text not null,
  usage_date date not null,
  count integer default 0,
  
  unique(ip_address, usage_date)
);

-- RLS for Guest Usage (Allow public access for IP tracking)
alter table guest_usage enable row level security;

create policy "Enable read access for all users"
on guest_usage for select
using (true);

create policy "Enable insert for all users"
on guest_usage for insert
with check (true);

create policy "Enable update for all users"
on guest_usage for update
using (true);

-- 5. Connected Accounts (Social Media Integration)
create table if not exists connected_accounts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  platform text not null, -- 'instagram', 'tiktok', etc.
  access_token text,
  refresh_token text,
  account_id text,
  account_name text,
  expires_at timestamp with time zone,
  
  unique(user_id, platform)
);

-- RLS for Connected Accounts
alter table connected_accounts enable row level security;

create policy "Users can view own connected accounts"
  on connected_accounts for select
  using (auth.uid() = user_id);

create policy "Users can insert own connected accounts"
  on connected_accounts for insert
  with check (auth.uid() = user_id);

create policy "Users can update own connected accounts"
  on connected_accounts for update
  using (auth.uid() = user_id);

create policy "Users can delete own connected accounts"
  on connected_accounts for delete
  using (auth.uid() = user_id);
