
-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  coin_balance integer default 100,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for history
create table history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  captions jsonb,
  hashtags jsonb,
  best_time text,
  viral_potential integer,
  platform text,
  mood text,
  music_recommendations jsonb,
  roast text,
  scores jsonb,
  improvements jsonb
);

alter table history enable row level security;

create policy "Users can view their own history."
  on history for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own history."
  on history for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own history."
  on history for delete
  using ( auth.uid() = user_id );

-- Create a table for transactions (optional but good for audit)
create table transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  amount integer not null, -- positive for purchase, negative for spend
  description text,
  payment_id text -- from Razorpay or similar
);

alter table transactions enable row level security;

create policy "Users can view their own transactions."
  on transactions for select
  using ( auth.uid() = user_id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, coin_balance)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 100);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- BACKFILL: Create profiles for users who signed up before this script was run
insert into public.profiles (id, full_name, avatar_url, coin_balance)
select 
  id, 
  raw_user_meta_data->>'full_name', 
  raw_user_meta_data->>'avatar_url', 
  100
from auth.users
on conflict (id) do nothing;
