export const ANIMATIONS = [
    { id: 'none', label: 'None', type: 'none' },

    // IN Animations
    { id: 'fadeIn', label: 'Fade In', type: 'in' },
    { id: 'scaleIn', label: 'Scale In', type: 'in' },
    { id: 'slideInLeft', label: 'Slide In Left', type: 'in' },
    { id: 'slideInRight', label: 'Slide In Right', type: 'in' },
    { id: 'slideInUp', label: 'Slide In Up', type: 'in' },
    { id: 'slideInDown', label: 'Slide In Down', type: 'in' },
    { id: 'rotateIn', label: 'Rotate In', type: 'in' },
    { id: 'rotateInCw', label: 'Rotate In CW', type: 'in' },
    { id: 'rotateInCcw', label: 'Rotate In CCW', type: 'in' },
    { id: 'bounceIn', label: 'Bounce In', type: 'in' },
    { id: 'elasticIn', label: 'Elastic In', type: 'in' },
    { id: 'flipInX', label: 'Flip In X', type: 'in' },
    { id: 'flipInY', label: 'Flip In Y', type: 'in' },
    { id: 'zoomIn', label: 'Zoom In', type: 'in' },
    { id: 'zoomInUp', label: 'Zoom In Up', type: 'in' },
    { id: 'zoomInDown', label: 'Zoom In Down', type: 'in' },
    { id: 'zoomInLeft', label: 'Zoom In Left', type: 'in' },
    { id: 'zoomInRight', label: 'Zoom In Right', type: 'in' },
    { id: 'rollIn', label: 'Roll In', type: 'in' },
    { id: 'lightSpeedInRight', label: 'Light Speed In', type: 'in' },

    // OUT Animations
    { id: 'fadeOut', label: 'Fade Out', type: 'out' },
    { id: 'scaleOut', label: 'Scale Out', type: 'out' },
    { id: 'slideOutLeft', label: 'Slide Out Left', type: 'out' },
    { id: 'slideOutRight', label: 'Slide Out Right', type: 'out' },
    { id: 'slideOutUp', label: 'Slide Out Up', type: 'out' },
    { id: 'slideOutDown', label: 'Slide Out Down', type: 'out' },
    { id: 'rotateOut', label: 'Rotate Out', type: 'out' },
    { id: 'rotateOutCw', label: 'Rotate Out CW', type: 'out' },
    { id: 'rotateOutCcw', label: 'Rotate Out CCW', type: 'out' },
    { id: 'bounceOut', label: 'Bounce Out', type: 'out' },
    { id: 'elasticOut', label: 'Elastic Out', type: 'out' },
    { id: 'flipOutX', label: 'Flip Out X', type: 'out' },
    { id: 'flipOutY', label: 'Flip Out Y', type: 'out' },
    { id: 'zoomOut', label: 'Zoom Out', type: 'out' },
    { id: 'zoomOutUp', label: 'Zoom Out Up', type: 'out' },
    { id: 'zoomOutDown', label: 'Zoom Out Down', type: 'out' },
    { id: 'zoomOutLeft', label: 'Zoom Out Left', type: 'out' },
    { id: 'zoomOutRight', label: 'Zoom Out Right', type: 'out' },
    { id: 'rollOut', label: 'Roll Out', type: 'out' },
    { id: 'lightSpeedOutRight', label: 'Light Speed Out', type: 'out' },

    // COMBO / LOOP Animations
    { id: 'pulse', label: 'Pulse', type: 'combo' },
    { id: 'shake', label: 'Shake', type: 'combo' },
    { id: 'swing', label: 'Swing', type: 'combo' },
    { id: 'tada', label: 'Tada', type: 'combo' },
    { id: 'wobble', label: 'Wobble', type: 'combo' },
    { id: 'jello', label: 'Jello', type: 'combo' },
    { id: 'heartbeat', label: 'Heartbeat', type: 'combo' },
    { id: 'flash', label: 'Flash', type: 'combo' },
    { id: 'rubberBand', label: 'Rubber Band', type: 'combo' },
    { id: 'headShake', label: 'Head Shake', type: 'combo' }
];
