export const FILTER_PRESETS = [
    { id: 'normal', name: 'Normal', values: {} },
    { id: 'simple', name: 'Simple', values: { brightness: 5, contrast: 5, saturation: 5 } },
    { id: 'boost', name: 'Boost', values: { brightness: 5, contrast: 10, saturation: 20 } },
    { id: 'oslo', name: 'Oslo', values: { temp: -10, contrast: 5, brightness: 5 } },
    { id: 'paris', name: 'Paris', values: { brightness: 5, contrast: -5, saturation: -10, temp: 5 } },
    { id: 'jakarta', name: 'Jakarta', values: { tint: 10, saturation: 10, contrast: 5 } },
    { id: 'toasty', name: 'Toasty', values: { temp: 20, brightness: -5, contrast: 10, sepia: 10 } },
    { id: 'subtle', name: 'Subtle', values: { saturation: -10, contrast: 5 } },
    { id: 'light', name: 'Light', values: { brightness: 15, contrast: -5 } },
    { id: 'fresh', name: 'Fresh', values: { brightness: 5, temp: -5, saturation: 10 } },
    { id: 'lively', name: 'Lively', values: { saturation: 20, contrast: 10, brightness: 5 } },
    { id: 'crisp', name: 'Crisp', values: { contrast: 20, saturation: 5, sharpen: 20 } },
    { id: 'fade', name: 'Fade', values: { fade: 30, contrast: -10 } },
    { id: 'new_york', name: 'New York', values: { grayscale: 10, contrast: 15, brightness: -5 } },
    { id: 'shade', name: 'Shade', values: { brightness: -10, contrast: 5 } },
    { id: 'summer', name: 'Summer', values: { temp: 15, saturation: 15, brightness: 5 } },
    { id: 'latte', name: 'Latte', values: { sepia: 20, brightness: 5, contrast: -5 } },
    { id: 'vintage', name: 'Vintage', values: { sepia: 40, contrast: 10, vignette: 30 } },
    { id: 'spring', name: 'Spring', values: { temp: -5, saturation: 15, brightness: 10, tint: 5 } },
    { id: 'antique', name: 'Antique', values: { sepia: 50, contrast: 5, brightness: -10, vignette: 20 } },
    { id: 'wash', name: 'Wash', values: { brightness: 10, contrast: -15, saturation: -10 } },
    { id: 'autumn', name: 'Autumn', values: { temp: 25, saturation: 10, contrast: 5 } },
    { id: 'disposable', name: 'Disposable', values: { contrast: 15, saturation: 10, grain: 30, vignette: 20 } },
    { id: 'lounge', name: 'Lounge', values: { temp: 10, brightness: -10, saturation: -10 } },
    { id: 'simple_cool', name: 'Simple Cool', values: { temp: -15, contrast: 5 } },
    { id: 'fade_cool', name: 'Fade Cool', values: { temp: -15, fade: 20 } },
    { id: 'boost_cool', name: 'Boost Cool', values: { temp: -15, saturation: 20, contrast: 10 } },
    { id: 'frosty', name: 'Frosty', values: { temp: -30, brightness: 10 } },
    { id: 'indigo', name: 'Indigo', values: { temp: -20, tint: 20, saturation: 10 } },
    { id: 'denim', name: 'Denim', values: { temp: -10, contrast: 10, saturation: -10, brightness: -5 } },
    { id: 'simple_warm', name: 'Simple Warm', values: { temp: 15, contrast: 5 } },
    { id: 'boost_warm', name: 'Boost Warm', values: { temp: 20, saturation: 20, contrast: 10 } },
    { id: 'fade_warm', name: 'Fade Warm', values: { temp: 20, fade: 20 } },
    { id: 'los_angeles', name: 'Los Angeles', values: { temp: 15, brightness: 10, contrast: 5 } },
    { id: 'abu_dhabi', name: 'Abu Dhabi', values: { temp: 30, contrast: 10, saturation: 5 } },
    { id: 'vintage_warm', name: 'Vintage Warm', values: { temp: 20, sepia: 20, contrast: 5 } },
    { id: 'butter', name: 'Butter', values: { temp: 10, brightness: 10, saturation: 5 } },
    { id: 'lemon', name: 'Lemon', values: { temp: 5, tint: -10, brightness: 10 } },
    { id: 'amber', name: 'Amber', values: { temp: 30, sepia: 10, contrast: 5 } },
    { id: 'soft_light', name: 'Soft Light', values: { brightness: 10, contrast: -10 } },
    { id: 'buenos_aires', name: 'Buenos Aires', values: { saturation: 20, temp: 10, contrast: 10 } },
    { id: 'cairo', name: 'Cairo', values: { temp: 20, brightness: 5, contrast: 5 } },
    { id: 'jaipur', name: 'Jaipur', values: { tint: 10, temp: 10, saturation: 15 } },
    { id: 'melbourne', name: 'Melbourne', values: { saturation: -20, contrast: 10 } },
    { id: 'lagos', name: 'Lagos', values: { contrast: 20, saturation: 10 } },
    { id: 'glow', name: 'Glow', values: { brightness: 15, saturation: 10, temp: 5 } },
    { id: 'midnight', name: 'Midnight', values: { brightness: -20, contrast: 10, saturation: -10 } },
    { id: 'dusk', name: 'Dusk', values: { temp: -10, tint: 10, brightness: -10 } },
    { id: 'honey', name: 'Honey', values: { temp: 20, brightness: 5 } },
    { id: 'blush', name: 'Blush', values: { tint: 20, temp: 5, brightness: 5 } },
    { id: 'sunset', name: 'Sunset', values: { temp: 30, tint: 10, contrast: 10 } },
    { id: 'dandelion', name: 'Dandelion', values: { temp: 15, brightness: 10 } },
    { id: 'graphite', name: 'Graphite', values: { grayscale: 100, contrast: 20 } },
    { id: 'gritty', name: 'Gritty', values: { grayscale: 100, contrast: 40, grain: 40 } },
    { id: 'tokyo', name: 'Tokyo', values: { grayscale: 100, brightness: 10 } },
    { id: 'greyscale', name: 'Greyscale', values: { grayscale: 100 } },
    { id: 'classic', name: 'Classic', values: { grayscale: 100, contrast: 10, sepia: 10 } },
];
