-- Create a table for watched domains
create table if not exists watched_domains (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  domain text not null,
  target_price decimal, -- Optional: if user wants to set a target
  current_price decimal, -- Optional: Snapshot of price when added
  status text default 'available', -- 'available', 'taken', 'premium'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, domain)
);

-- Set up Row Level Security (RLS)
alter table watched_domains enable row level security;

create policy "Users can view their own watched domains."
  on watched_domains for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own watched domains."
  on watched_domains for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own watched domains."
  on watched_domains for delete
  using ( auth.uid() = user_id );

create policy "Users can update their own watched domains."
  on watched_domains for update
  using ( auth.uid() = user_id );
